import java.awt.*;
import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class ReportExporter {
    public static final String REPORTS_DIR = "reports";
    private static final DateTimeFormatter TIMESTAMP_FORMAT = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");

    /**
     * Exports a report in text format
     * @param user The user for whom the report is generated
     * @param content The report content
     * @return The filename of the saved report or null if export failed
     */
    public String exportTextReport(User user, String content) {
        createReportsDirectory();

        String fileName = String.format("%s/%s_report_%s.txt",
                REPORTS_DIR,
                user.getUserID(),
                LocalDateTime.now().format(TIMESTAMP_FORMAT));

        try (PrintWriter out = new PrintWriter(fileName)) {
            out.println(content);
            System.out.println("Text report successfully exported to: " + fileName);
            return fileName;
        } catch (FileNotFoundException e) {
            System.err.println("Error exporting report: " + e.getMessage());
            return null;
        }
    }

    /**
     * Exports a report in HTML format with enhanced styling
     * @param user The user for whom the report is generated
     * @param content The report content in HTML format
     * @return The filename of the saved report or null if export failed
     */
    public String exportHtmlReport(User user, String content) {
        createReportsDirectory();

        String fileName = String.format("%s/%s_report_%s.html",
                REPORTS_DIR,
                user.getUserID(),
                LocalDateTime.now().format(TIMESTAMP_FORMAT));

        String htmlContent = "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<head>\n"
                + "    <meta charset='UTF-8'>\n"
                + "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
                + "    <title>Learning Report for " + user.getName() + "</title>\n"
                + "    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css'>\n"
                + "    <style>\n"
                + "        :root {\n"
                + "            --primary-color: #4285f4;\n"
                + "            --secondary-color: #34a853;\n"
                + "            --accent-color: #fbbc05;\n"
                + "            --warning-color: #ea4335;\n"
                + "            --light-bg: #f8f9fa;\n"
                + "            --dark-bg: #202124;\n"
                + "            --border-color: #dadce0;\n"
                + "            --card-shadow: 0 4px 6px rgba(0,0,0,0.1);\n"
                + "            --transition-speed: 0.3s;\n"
                + "        }\n"
                + "        * { box-sizing: border-box; }\n"
                + "        body {\n"
                + "            font-family: 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;\n"
                + "            margin: 0;\n"
                + "            padding: 0;\n"
                + "            color: #333;\n"
                + "            background-color: #f5f5f5;\n"
                + "            line-height: 1.6;\n"
                + "        }\n"
                + "        .container {\n"
                + "            max-width: 1100px;\n"
                + "            margin: 0 auto;\n"
                + "            padding: 20px;\n"
                + "            background-color: white;\n"
                + "            box-shadow: 0 2px 25px rgba(0,0,0,0.1);\n"
                + "            border-radius: 12px;\n"
                + "            margin-top: 30px;\n"
                + "            margin-bottom: 30px;\n"
                + "        }\n"
                + "        .header {\n"
                + "            background: linear-gradient(135deg, var(--primary-color), #5c6bc0);\n"
                + "            color: white;\n"
                + "            padding: 40px 30px;\n"
                + "            border-radius: 12px 12px 0 0;\n"
                + "            text-align: center;\n"
                + "            position: relative;\n"
                + "            overflow: hidden;\n"
                + "            margin-bottom: 30px;\n"
                + "            box-shadow: 0 4px 15px rgba(0,0,0,0.1);\n"
                + "        }\n"
                + "        .header:before {\n"
                + "            content: '';\n"
                + "            position: absolute;\n"
                + "            top: -10px;\n"
                + "            left: -10px;\n"
                + "            right: -10px;\n"
                + "            bottom: -10px;\n"
                + "            background: linear-gradient(45deg, rgba(255,255,255,0.1) 25%, transparent 25%, transparent 50%, rgba(255,255,255,0.1) 50%, rgba(255,255,255,0.1) 75%, transparent 75%);\n"
                + "            background-size: 20px 20px;\n"
                + "            z-index: 1;\n"
                + "            opacity: 0.3;\n"
                + "            animation: backgroundMove 20s linear infinite;\n"
                + "        }\n"
                + "        @keyframes backgroundMove {\n"
                + "            0% { background-position: 0 0; }\n"
                + "            100% { background-position: 50px 50px; }\n"
                + "        }\n"
                + "        .header-content {\n"
                + "            position: relative;\n"
                + "            z-index: 2;\n"
                + "        }\n"
                + "        h1 {\n"
                + "            margin: 0;\n"
                + "            font-size: 2.5rem;\n"
                + "            font-weight: 300;\n"
                + "            letter-spacing: 1px;\n"
                + "            text-shadow: 1px 1px 3px rgba(0,0,0,0.2);\n"
                + "        }\n"
                + "        .date {\n"
                + "            font-style: italic;\n"
                + "            opacity: 0.8;\n"
                + "            margin-top: 10px;\n"
                + "        }\n"
                + "        .section {\n"
                + "            margin: 30px 0;\n"
                + "            padding: 25px;\n"
                + "            background: white;\n"
                + "            border-radius: 12px;\n"
                + "            box-shadow: var(--card-shadow);\n"
                + "            border-left: 4px solid var(--primary-color);\n"
                + "            transition: transform var(--transition-speed), box-shadow var(--transition-speed);\n"
                + "        }\n"
                + "        .section:hover {\n"
                + "            transform: translateY(-5px);\n"
                + "            box-shadow: 0 8px 15px rgba(0,0,0,0.1);\n"
                + "        }\n"
                + "        .section h2 {\n"
                + "            margin-top: 0;\n"
                + "            color: var(--primary-color);\n"
                + "            font-weight: 500;\n"
                + "            border-bottom: 1px solid var(--border-color);\n"
                + "            padding-bottom: 10px;\n"
                + "            display: flex;\n"
                + "            align-items: center;\n"
                + "        }\n"
                + "        .section h2 i {\n"
                + "            margin-right: 10px;\n"
                + "            opacity: 0.8;\n"
                + "        }\n"
                + "        .user-info {\n"
                + "            border-left: 4px solid #5c6bc0;\n"
                + "        }\n"
                + "        .info-card {\n"
                + "            display: flex;\n"
                + "            flex-wrap: wrap;\n"
                + "            background: var(--light-bg);\n"
                + "            border-radius: 10px;\n"
                + "            padding: 20px;\n"
                + "            box-shadow: inset 0 1px 3px rgba(0,0,0,0.05);\n"
                + "        }\n"
                + "        .user-details {\n"
                + "            flex: 1;\n"
                + "            min-width: 250px;\n"
                + "        }\n"
                + "        .user-details table {\n"
                + "            width: 100%;\n"
                + "            border-collapse: collapse;\n"
                + "        }\n"
                + "        .user-details table td {\n"
                + "            padding: 12px 8px;\n"
                + "            border-bottom: 1px solid rgba(0,0,0,0.05);\n"
                + "        }\n"
                + "        .user-details table tr:last-child td {\n"
                + "            border-bottom: none;\n"
                + "        }\n"
                + "        .user-details table td:first-child {\n"
                + "            font-weight: 600;\n"
                + "            width: 40%;\n"
                + "            color: #555;\n"
                + "        }\n"
                + "        .courses-list {\n"
                + "            display: grid;\n"
                + "            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));\n"
                + "            gap: 20px;\n"
                + "        }\n"
                + "        .course-item {\n"
                + "            background: var(--light-bg);\n"
                + "            border-radius: 10px;\n"
                + "            padding: 20px;\n"
                + "            box-shadow: 0 2px 8px rgba(0,0,0,0.05);\n"
                + "            transition: transform var(--transition-speed), box-shadow var(--transition-speed);\n"
                + "            border-top: 3px solid var(--primary-color);\n"
                + "        }\n"
                + "        .course-item:hover {\n"
                + "            transform: translateY(-5px);\n"
                + "            box-shadow: 0 8px 15px rgba(0,0,0,0.1);\n"
                + "        }\n"
                + "        .course-header {\n"
                + "            display: flex;\n"
                + "            justify-content: space-between;\n"
                + "            align-items: flex-start;\n"
                + "            margin-bottom: 15px;\n"
                + "        }\n"
                + "        .course-header h3 {\n"
                + "            margin: 0;\n"
                + "            font-size: 1.2rem;\n"
                + "            color: #333;\n"
                + "            flex: 1;\n"
                + "        }\n"
                + "        .difficulty {\n"
                + "            padding: 4px 10px;\n"
                + "            border-radius: 20px;\n"
                + "            font-size: 0.75rem;\n"
                + "            font-weight: 600;\n"
                + "            text-transform: uppercase;\n"
                + "            letter-spacing: 0.5px;\n"
                + "        }\n"
                + "        .beginner {\n"
                + "            background-color: #c8e6c9;\n"
                + "            color: #2e7d32;\n"
                + "        }\n"
                + "        .intermediate {\n"
                + "            background-color: #fff9c4;\n"
                + "            color: #f57f17;\n"
                + "        }\n"
                + "        .advanced {\n"
                + "            background-color: #ffcdd2;\n"
                + "            color: #c62828;\n"
                + "        }\n"
                + "        .course-meta {\n"
                + "            display: flex;\n"
                + "            justify-content: space-between;\n"
                + "            margin-bottom: 15px;\n"
                + "            font-size: 0.9rem;\n"
                + "            color: #666;\n"
                + "        }\n"
                + "        .category {\n"
                + "            display: inline-block;\n"
                + "            background: rgba(0,0,0,0.05);\n"
                + "            padding: 3px 10px;\n"
                + "            border-radius: 4px;\n"
                + "            font-size: 0.85rem;\n"
                + "        }\n"
                + "        .progress-container {\n"
                + "            display: flex;\n"
                + "            align-items: center;\n"
                + "            margin-top: 10px;\n"
                + "        }\n"
                + "        .progress-bar {\n"
                + "            flex-grow: 1;\n"
                + "            height: 12px;\n"
                + "            background-color: #e0e0e0;\n"
                + "            border-radius: 6px;\n"
                + "            overflow: hidden;\n"
                + "            margin-right: 10px;\n"
                + "            box-shadow: inset 0 1px 2px rgba(0,0,0,0.1);\n"
                + "        }\n"
                + "        .progress-fill {\n"
                + "            height: 100%;\n"
                + "            background-color: var(--primary-color);\n"
                + "            border-radius: 6px;\n"
                + "            transition: width 1s ease;\n"
                + "            position: relative;\n"
                + "            overflow: hidden;\n"
                + "        }\n"
                + "        .progress-fill:after {\n"
                + "            content: '';\n"
                + "            position: absolute;\n"
                + "            top: 0;\n"
                + "            left: 0;\n"
                + "            bottom: 0;\n"
                + "            right: 0;\n"
                + "            background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.2) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.2) 50%, rgba(255, 255, 255, 0.2) 75%, transparent 75%, transparent);\n"
                + "            background-size: 15px 15px;\n"
                + "            animation: progressAnimation 1s linear infinite;\n"
                + "        }\n"
                + "        @keyframes progressAnimation {\n"
                + "            0% { background-position: 0 0; }\n"
                + "            100% { background-position: 15px 0; }\n"
                + "        }\n"
                + "        .progress-fill.complete {\n"
                + "            background-color: var(--secondary-color);\n"
                + "        }\n"
                + "        .progress-fill.good {\n"
                + "            background-color: var(--accent-color);\n"
                + "        }\n"
                + "        .progress-fill.needs-work {\n"
                + "            background-color: var(--warning-color);\n"
                + "        }\n"
                + "        .progress-text {\n"
                + "            font-weight: bold;\n"
                + "            font-size: 0.9rem;\n"
                + "            width: 40px;\n"
                + "            text-align: right;\n"
                + "        }\n"
                + "        .progress-text.complete {\n"
                + "            color: var(--secondary-color);\n"
                + "        }\n"
                + "        .progress-text.good {\n"
                + "            color: var(--accent-color);\n"
                + "        }\n"
                + "        .progress-text.needs-work {\n"
                + "            color: var(--warning-color);\n"
                + "        }\n"
                + "        .learning-style {\n"
                + "            background: linear-gradient(to right, #f3e5f5, #e8f5e9);\n"
                + "            border-radius: 10px;\n"
                + "            padding: 25px;\n"
                + "            box-shadow: 0 2px 10px rgba(0,0,0,0.05);\n"
                + "        }\n"
                + "        .primary-style {\n"
                + "            font-size: 1.2rem;\n"
                + "            color: #333;\n"
                + "            margin-bottom: 20px;\n"
                + "        }\n"
                + "        .style-recommendations {\n"
                + "            background: rgba(255,255,255,0.7);\n"
                + "            padding: 20px;\n"
                + "            border-radius: 8px;\n"
                + "            box-shadow: 0 1px 5px rgba(0,0,0,0.05);\n"
                + "        }\n"
                + "        .style-recommendations h4 {\n"
                + "            margin-top: 0;\n"
                + "            color: #555;\n"
                + "            border-bottom: 1px solid rgba(0,0,0,0.1);\n"
                + "            padding-bottom: 10px;\n"
                + "            margin-bottom: 15px;\n"
                + "        }\n"
                + "        .benefits-list {\n"
                + "            padding-left: 20px;\n"
                + "            margin-bottom: 0;\n"
                + "        }\n"
                + "        .benefits-list li {\n"
                + "            margin-bottom: 10px;\n"
                + "            position: relative;\n"
                + "            padding-left: 5px;\n"
                + "        }\n"
                + "        .benefits-list li:last-child {\n"
                + "            margin-bottom: 0;\n"
                + "        }\n"
                + "        .analysis-card {\n"
                + "            background: var(--light-bg);\n"
                + "            border-radius: 10px;\n"
                + "            padding: 25px;\n"
                + "            box-shadow: 0 2px 10px rgba(0,0,0,0.05);\n"
                + "        }\n"
                + "        .metrics-cards {\n"
                + "            display: flex;\n"
                + "            justify-content: space-between;\n"
                + "            flex-wrap: wrap;\n"
                + "            gap: 20px;\n"
                + "        }\n"
                + "        .metric-card {\n"
                + "            flex: 1;\n"
                + "            min-width: 180px;\n"
                + "            background: white;\n"
                + "            border-radius: 10px;\n"
                + "            padding: 25px;\n"
                + "            text-align: center;\n"
                + "            box-shadow: 0 4px 15px rgba(0,0,0,0.08);\n"
                + "            transition: transform var(--transition-speed), box-shadow var(--transition-speed);\n"
                + "        }\n"
                + "        .metric-card:hover {\n"
                + "            transform: translateY(-5px);\n"
                + "            box-shadow: 0 8px 20px rgba(0,0,0,0.1);\n"
                + "        }\n"
                + "        .metric-card.completed {\n"
                + "            border-top: 3px solid var(--secondary-color);\n"
                + "        }\n"
                + "        .metric-card.in-progress {\n"
                + "            border-top: 3px solid var(--accent-color);\n"
                + "        }\n"
                + "        .metric-card.hours {\n"
                + "            border-top: 3px solid var(--primary-color);\n"
                + "        }\n"
                + "        .metric-icon {\n"
                + "            font-size: 2.2rem;\n"
                + "            margin-bottom: 15px;\n"
                + "            color: #555;\n"
                + "        }\n"
                + "        .metric-value {\n"
                + "            font-size: 2.8rem;\n"
                + "            font-weight: 700;\n"
                + "            color: #333;\n"
                + "            line-height: 1.2;\n"
                + "        }\n"
                + "        .metric-label {\n"
                + "            font-size: 0.9rem;\n"
                + "            color: #666;\n"
                + "            margin-top: 8px;\n"
                + "        }\n"
                + "        .streak-container {\n"
                + "            display: flex;\n"
                + "            align-items: center;\n"
                + "            margin-top: 30px;\n"
                + "            background: linear-gradient(to right, #fff8e1, #ffebee);\n"
                + "            padding: 20px;\n"
                + "            border-radius: 10px;\n"
                + "            box-shadow: 0 2px 10px rgba(0,0,0,0.05);\n"
                + "            animation: pulse 2s infinite;\n"
                + "        }\n"
                + "        @keyframes pulse {\n"
                + "            0% { box-shadow: 0 0 0 0 rgba(255, 87, 34, 0.4); }\n"
                + "            70% { box-shadow: 0 0 0 10px rgba(255, 87, 34, 0); }\n"
                + "            100% { box-shadow: 0 0 0 0 rgba(255, 87, 34, 0); }\n"
                + "        }\n"
                + "        .streak-icon {\n"
                + "            font-size: 2.8rem;\n"
                + "            margin-right: 20px;\n"
                + "        }\n"
                + "        .streak-count {\n"
                + "            font-size: 1.4rem;\n"
                + "            font-weight: 700;\n"
                + "            color: #ff5722;\n"
                + "        }\n"
                + "        .streak-message {\n"
                + "            color: #666;\n"
                + "            margin-top: 5px;\n"
                + "        }\n"
                + "        .recommendations-list {\n"
                + "            display: grid;\n"
                + "            grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));\n"
                + "            gap: 25px;\n"
                + "        }\n"
                + "        .recommendation {\n"
                + "            background: #f1f8e9;\n"
                + "            border-radius: 10px;\n"
                + "            padding: 25px;\n"
                + "            box-shadow: 0 4px 15px rgba(0,0,0,0.05);\n"
                + "            transition: transform var(--transition-speed), box-shadow var(--transition-speed);\n"
                + "            position: relative;\n"
                + "            overflow: hidden;\n"
                + "        }\n"
                + "        .recommendation:hover {\n"
                + "            transform: translateY(-7px);\n"
                + "            box-shadow: 0 15px 30px rgba(0,0,0,0.1);\n"
                + "        }\n"
                + "        .recommendation::before {\n"
                + "            content: '';\n"
                + "            position: absolute;\n"
                + "            top: -20px;\n"
                + "            right: -20px;\n"
                + "            width: 60px;\n"
                + "            height: 60px;\n"
                + "            background: var(--secondary-color);\n"
                + "            transform: rotate(45deg);\n"
                + "            opacity: 0.1;\n"
                + "        }\n"
                + "        .rec-header {\n"
                + "            display: flex;\n"
                + "            justify-content: space-between;\n"
                + "            align-items: flex-start;\n"
                + "            margin-bottom: 15px;\n"
                + "        }\n"
                + "        .rec-header h3 {\n"
                + "            margin: 0;\n"
                + "            color: #333;\n"
                + "            flex: 1;\n"
                + "            font-size: 1.3rem;\n"
                + "        }\n"
                + "        .rec-category {\n"
                + "            display: inline-block;\n"
                + "            background: rgba(0,0,0,0.05);\n"
                + "            padding: 5px 12px;\n"
                + "            border-radius: 20px;\n"
                + "            font-size: 0.85rem;\n"
                + "            margin-bottom: 15px;\n"
                + "            color: #555;\n"
                + "            font-weight: 500;\n"
                + "        }\n"
                + "        .rec-description {\n"
                + "            color: #555;\n"
                + "            font-size: 0.95rem;\n"
                + "            margin-bottom: 20px;\n"
                + "            line-height: 1.5;\n"
                + "        }\n"
                + "        .rec-meta {\n"
                + "            display: flex;\n"
                + "            justify-content: space-between;\n"
                + "            align-items: center;\n"
                + "        }\n"
                + "        .enroll-btn {\n"
                + "            background: var(--primary-color);\n"
                + "            color: white;\n"
                + "            text-decoration: none;\n"
                + "            padding: 10px 20px;\n"
                + "            border-radius: 25px;\n"
                + "            font-weight: 500;\n"
                + "            font-size: 0.95rem;\n"
                + "            transition: all 0.3s;\n"
                + "            border: none;\n"
                + "            cursor: pointer;\n"
                + "            box-shadow: 0 4px 6px rgba(0,0,0,0.1);\n"
                + "            display: inline-block;\n"
                + "            width: 100%;\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "        .enroll-btn:hover {\n"
                + "            background: #3367d6;\n"
                + "            transform: translateY(-2px);\n"
                + "            box-shadow: 0 6px 10px rgba(0,0,0,0.15);\n"
                + "        }\n"
                + "        .enroll-btn:active {\n"
                + "            transform: translateY(1px);\n"
                + "            box-shadow: 0 2px 5px rgba(0,0,0,0.1);\n"
                + "        }\n"
                + "        .enroll-btn.enrolled {\n"
                + "            background: var(--secondary-color);\n"
                + "            cursor: default;\n"
                + "        }\n"
                + "        .no-data {\n"
                + "            background: var(--light-bg);\n"
                + "            padding: 25px;\n"
                + "            border-radius: 10px;\n"
                + "            text-align: center;\n"
                + "            color: #666;\n"
                + "            font-style: italic;\n"
                + "        }\n"
                + "        .footer {\n"
                + "            margin-top: 50px;\n"
                + "            text-align: center;\n"
                + "            color: #666;\n"
                + "            background: var(--light-bg);\n"
                + "            padding: 30px;\n"
                + "            border-radius: 0 0 12px 12px;\n"
                + "            position: relative;\n"
                + "        }\n"
                + "        .footer a {\n"
                + "            color: var(--primary-color);\n"
                + "            text-decoration: none;\n"
                + "            transition: color 0.2s;\n"
                + "        }\n"
                + "        .footer a:hover {\n"
                + "            color: #3367d6;\n"
                + "            text-decoration: underline;\n"
                + "        }\n"
                + "        .copyright {\n"
                + "            font-size: 0.85rem;\n"
                + "            margin-top: 20px;\n"
                + "            color: #999;\n"
                + "        }\n"
                + "        /* Modal styles */\n"
                + "        .modal {\n"
                + "            display: none;\n"
                + "            position: fixed;\n"
                + "            top: 0;\n"
                + "            left: 0;\n"
                + "            width: 100%;\n"
                + "            height: 100%;\n"
                + "            background-color: rgba(0,0,0,0.7);\n"
                + "            z-index: 1000;\n"
                + "            align-items: center;\n"
                + "            justify-content: center;\n"
                + "        }\n"
                + "        .modal-content {\n"
                + "            background-color: white;\n"
                + "            padding: 30px;\n"
                + "            border-radius: 10px;\n"
                + "            max-width: 500px;\n"
                + "            width: 90%;\n"
                + "            box-shadow: 0 5px 30px rgba(0,0,0,0.3);\n"
                + "            position: relative;\n"
                + "            animation: modalOpen 0.3s ease-out;\n"
                + "        }\n"
                + "        @keyframes modalOpen {\n"
                + "            from { opacity: 0; transform: scale(0.8); }\n"
                + "            to { opacity: 1; transform: scale(1); }\n"
                + "        }\n"
                + "        .modal-header {\n"
                + "            display: flex;\n"
                + "            justify-content: space-between;\n"
                + "            align-items: center;\n"
                + "            margin-bottom: 20px;\n"
                + "        }\n"
                + "        .modal-title {\n"
                + "            margin: 0;\n"
                + "            color: #333;\n"
                + "            font-size: 1.5rem;\n"
                + "        }\n"
                + "        .close-modal {\n"
                + "            background: none;\n"
                + "            border: none;\n"
                + "            font-size: 1.5rem;\n"
                + "            cursor: pointer;\n"
                + "            color: #999;\n"
                + "        }\n"
                + "        .close-modal:hover {\n"
                + "            color: #333;\n"
                + "        }\n"
                + "        .enrollment-success {\n"
                + "            text-align: center;\n"
                + "            padding: 20px 0;\n"
                + "        }\n"
                + "        .success-icon {\n"
                + "            font-size: 3rem;\n"
                + "            color: var(--secondary-color);\n"
                + "            margin-bottom: 20px;\n"
                + "        }\n"
                + "        .success-message {\n"
                + "            font-size: 1.2rem;\n"
                + "            margin-bottom: 20px;\n"
                + "            color: #333;\n"
                + "        }\n"
                + "        .modal-footer {\n"
                + "            text-align: center;\n"
                + "            margin-top: 30px;\n"
                + "        }\n"
                + "        .confirm-btn {\n"
                + "            background: var(--secondary-color);\n"
                + "            color: white;\n"
                + "            border: none;\n"
                + "            padding: 10px 25px;\n"
                + "            border-radius: 25px;\n"
                + "            font-weight: 500;\n"
                + "            cursor: pointer;\n"
                + "            transition: all 0.3s;\n"
                + "        }\n"
                + "        .confirm-btn:hover {\n"
                + "            background: #2d7d46;\n"
                + "            transform: translateY(-2px);\n"
                + "            box-shadow: 0 4px 8px rgba(0,0,0,0.1);\n"
                + "        }\n"
                + "        @media (max-width: 768px) {\n"
                + "            .container {\n"
                + "                padding: 15px;\n"
                + "                margin-top: 15px;\n"
                + "                margin-bottom: 15px;\n"
                + "            }\n"
                + "            .metrics-cards, .courses-list, .recommendations-list {\n"
                + "                grid-template-columns: 1fr;\n"
                + "            }\n"
                + "            .metric-card {\n"
                + "                margin-bottom: 15px;\n"
                + "            }\n"
                + "            .header {\n"
                + "                padding: 30px 20px;\n"
                + "            }\n"
                + "            h1 {\n"
                + "                font-size: 1.8rem;\n"
                + "            }\n"
                + "            .section {\n"
                + "                padding: 20px 15px;\n"
                + "                margin: 20px 0;\n"
                + "            }\n"
                + "            .recommendation {\n"
                + "                padding: 20px;\n"
                + "            }\n"
                + "            .rec-header h3 {\n"
                + "                font-size: 1.1rem;\n"
                + "            }\n"
                + "            .streak-container {\n"
                + "                flex-direction: column;\n"
                + "                text-align: center;\n"
                + "            }\n"
                + "            .streak-icon {\n"
                + "                margin-right: 0;\n"
                + "                margin-bottom: 10px;\n"
                + "            }\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "<div class='container'>\n"
                + content
                + "</div>\n"
                + "<!-- Enrollment Modal -->\n"
                + "<div id='enrollmentModal' class='modal'>\n"
                + "    <div class='modal-content'>\n"
                + "        <div class='modal-header'>\n"
                + "            <h3 class='modal-title'>Course Enrollment</h3>\n"
                + "            <button class='close-modal'>&times;</button>\n"
                + "        </div>\n"
                + "        <div class='enrollment-success'>\n"
                + "            <div class='success-icon'><i class='fas fa-check-circle'></i></div>\n"
                + "            <p class='success-message'>You have successfully enrolled in <span id='enrolledCourseName'></span>!</p>\n"
                + "            <p>You can start learning right away. The course has been added to your dashboard.</p>\n"
                + "        </div>\n"
                + "        <div class='modal-footer'>\n"
                + "            <button class='confirm-btn'>Go to Dashboard</button>\n"
                + "        </div>\n"
                + "    </div>\n"
                + "</div>\n"
                + "<!-- Font Awesome Icons -->\n"
                + "<script src='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js'></script>\n"
                + "<!-- Enrollment Functionality -->\n"
                + "<script>\n"
                + "    document.addEventListener('DOMContentLoaded', function() {\n"
                + "        // Get all enroll buttons\n"
                + "        const enrollButtons = document.querySelectorAll('.enroll-btn');\n"
                + "        const modal = document.getElementById('enrollmentModal');\n"
                + "        const closeModal = document.querySelector('.close-modal');\n"
                + "        const confirmBtn = document.querySelector('.confirm-btn');\n"
                + "        const enrolledCourseName = document.getElementById('enrolledCourseName');\n"
                + "        \n"
                + "        // Add click event to all enroll buttons\n"
                + "        enrollButtons.forEach(button => {\n"
                + "            button.addEventListener('click', function(e) {\n"
                + "                e.preventDefault();\n"
                + "                const courseId = this.getAttribute('data-course-id');\n"
                + "                const courseTitle = this.closest('.recommendation').querySelector('h3').textContent;\n"
                + "                \n"
                + "                // Simulate API call to enroll in course\n"
                + "                console.log(`Enrolling in course: ${courseId}`);\n"
                + "                \n"
                + "                // Show success message with course name\n"
                + "                enrolledCourseName.textContent = courseTitle;\n"
                + "                \n"
                + "                // Update button state\n"
                + "                this.textContent = 'Enrolled';\n"
                + "                this.classList.add('enrolled');\n"
                + "                this.disabled = true;\n"
                + "                \n"
                + "                // Show modal\n"
                + "                modal.style.display = 'flex';\n"
                + "                \n"
                + "                // Add to user's enrolled courses (simulation)\n"
                + "                const userId = '" + user.getUserID() + "';\n"
                + "                const userName = '" + user.getName() + "';\n"
                + "                console.log(`User ${userName} (${userId}) enrolled in course ${courseId}`);\n"
                + "                \n"
                + "                // You would typically make an API call here:\n"
                + "                // fetch('/api/enroll', {\n"
                + "                //     method: 'POST',\n"
                + "                //     headers: { 'Content-Type': 'application/json' },\n"
                + "                //     body: JSON.stringify({ userId, courseId })\n"
                + "                // })\n"
                + "                // .then(response => response.json())\n"
                + "                // .then(data => console.log('Enrollment successful:', data))\n"
                + "                // .catch(error => console.error('Enrollment failed:', error));\n"
                + "            });\n"
                + "        });\n"
                + "        \n"
                + "        // Close modal when clicking close button\n"
                + "        closeModal.addEventListener('click', function() {\n"
                + "            modal.style.display = 'none';\n"
                + "        });\n"
                + "        \n"
                + "        // Close modal when clicking confirm button\n"
                + "        confirmBtn.addEventListener('click', function() {\n"
                + "            modal.style.display = 'none';\n"
                + "            // Redirect to dashboard (simulation)\n"
                + "            console.log('Redirecting to dashboard...');\n"
                + "            // Uncomment to redirect in a real application:\n"
                + "            // window.location.href = '/dashboard';\n"
                + "        });\n"
                + "        \n"
                + "        // Close modal when clicking outside of it\n"
                + "        window.addEventListener('click', function(event) {\n"
                + "            if (event.target === modal) {\n"
                + "                modal.style.display = 'none';\n"
                + "            }\n"
                + "        });\n"
                + "        \n"
                + "        // Animate progress bars on load\n"
                + "        const progressBars = document.querySelectorAll('.progress-fill');\n"
                + "        progressBars.forEach(bar => {\n"
                + "            const width = bar.style.width;\n"
                + "            bar.style.width = '0%';\n"
                + "            setTimeout(() => {\n"
                + "                bar.style.width = width;\n"
                + "            }, 300);\n"
                + "        });\n"
                + "    });\n"
                + "</script>\n"
                + "</body>\n"
                + "</html>";

        try (PrintWriter out = new PrintWriter(fileName)) {
            out.println(htmlContent);
            System.out.println("HTML report successfully exported to: " + fileName);
            return fileName;
        } catch (FileNotFoundException e) {
            System.err.println("Error exporting HTML report: " + e.getMessage());
            return null;
        }
    }

    /**
     * Creates the reports directory if it doesn't exist
     */
    private void createReportsDirectory() {
        File dir = new File(REPORTS_DIR);
        if (!dir.exists()) {
            boolean created = dir.mkdir();
            if (created) {
                System.out.println("Reports directory created successfully");
            } else {
                System.err.println("Failed to create reports directory");
            }
        }
    }

    /**
     * Opens a file with the system's default application
     * @param filePath Path to the file to open
     * @return true if the file was successfully opened
     */
    public boolean openFile(String filePath) {
        if (filePath == null || !new File(filePath).exists()) {
            System.err.println("File does not exist: " + filePath);
            return false;
        }

        try {
            File file = new File(filePath);
            Desktop desktop = Desktop.getDesktop();
            if (desktop.isSupported(Desktop.Action.OPEN)) {
                desktop.open(file);
                return true;
            } else {
                System.err.println("Desktop open not supported on this platform");
                return false;
            }
        } catch (IOException e) {
            System.err.println("Error opening file: " + e.getMessage());
            return false;
        }
    }

    /**
     * Generates and opens a preview for a report in the specified format
     * @param user The user for whom the report is generated
     * @param content The report content
     * @param format The format to preview ("txt", "text", or "html")
     * @return true if preview was successfully opened
     */
    public boolean previewReport(User user, String content, String format) {
        String filePath = null;

        switch (format.toLowerCase()) {
            case "txt":
            case "text":
                filePath = exportTextReport(user, content);
                break;
            case "html":
                filePath = exportHtmlReport(user, content);
                break;
            default:
                System.err.println("Unsupported format: " + format);
                return false;
        }

        return openFile(filePath);
    }
}